project.name=intyg
artifact.name=rehabstod
artifact.version=2.5.0.6
sbom.aggregation.module=rehabstod-web
sbom.aggregation.path=web
git.url=https://github.com/sklintyg/rehabstod.git
git.branch=main
builder.image=app-builder-image
builder.image.tag=25.0.3
runtime.image=springboot-base
runtime.image.tag=25.0.1
build.args=build spotlessCheck testAggregateTestReport
sonarqube.args=