project.name=intyg
artifact.name=rehabstod
artifact.version=2.4.0.4
sbom.aggregation.module=rehabstod-web
sbom.aggregation.path=web
git.url=https://github.com/sklintyg/rehabstod.git
git.branch=main
builder.image=app-builder-image
builder.image.tag=21.0.6
runtime.image=springboot-base
runtime.image.tag=21.0.2
build.args=build spotlessCheck testAggregateTestReport
sonarqube.args=