@startuml
actor Läkare
Läkare -> Rehabstöd: Väljer att visa sina sjukfall på Vårdenhet
activate Rehabstöd
    Rehabstöd -> Intygstjänsten: ListActiveSickLeavesForCareUnit

    database Databas
    activate Intygstjänsten
        Intygstjänsten -> HSA: Begär hsaId för underord. mottagningar.
        activate HSA
            HSA --> Intygstjänsten: Lista av hsaId. för underord. mottagningar.
        deactivate HSA
        |||
        |||
        Intygstjänsten -> Databas: Hämta aktiva intyg för hsaIdn
        Databas --> Intygstjänsten: Intygsdata
        Intygstjänsten --> Rehabstöd: Intygsdata
    deactivate Intygstjänsten
    Rehabstöd -> Rehabstöd: Sammanställer sjukfall utifrån intyg
    Rehabstöd -> Rehabstöd: Filtrerar på läkaren
    Rehabstöd -> Läkare: Visar läkarens sjukfall på vårdenheten
deactivate Rehabstöd
@enduml