@startuml
actor Läkare
Läkare -> Rehabstöd: Utför urval i GUI
Rehabstöd -> Intygstjänsten: SokSjukfall (TjK)
Intygstjänsten -> HSA: Begär vårdenh. för överordnad vårdgiv.
HSA -> Intygstjänsten: List av vårdenh. för överordnad vårdgiv.
Intygstjänsten -> Intygstjänsten: Sammanställ sjukfall
Intygstjänsten -> Intygstjänsten: Filtrera på läkaren
Intygstjänsten -> Rehabstöd: Lista av sjukfall (TjK)
Rehabstöd -> Läkare: Visa sjukfall i GUI
@enduml